var setting = {
	value:{
		main:{
			canvasDiv:{
				id:"canvasDiv",
			},
			mask:{
				id:"mask",
			},
		},
		canvas:{
			color:"rgba(0, 0, 0, 1)",
			bgColor:"rgba(255, 255, 255, 1)",
			lineCap:"round",
			lineJoin:"round",
			width:800,
			height:600,
			offsetX:25,
			offsetY:25,
			border:1,
			lineWidth:50,
			lineWidthMin:1,
			lineWidhtMax:100,
			main:{
				id:"canvasMain",
				className:"canvas",
			},
			process:{
				id:"canvasProcess",
				className:"canvas",
			},
			glass:{
				id:"canvasGlass",
				className:"canvas",
			},
			temp:{
				id:"canvasTemp",
			},
			record:{
				size:10,
			},
			tool:{
				lineWidth:{
					id:"toolLineWidth",
				},
				path:{
					id:"toolPath",
					cursor:"crosshair",
				},
				eraser:{
					id:"toolEraser",
					cursor:"crosshair",
				},
				line:{
					id:"toolLine",
					cursor:"crosshair",
				},
				rect:{
					id:"toolRect",
					cursor:"crosshair",
				},
				circle:{
					id:"toolCircle",
					cursor:"crosshair",
				},
				select:{
					id:"toolSelect",
					cursor:"crosshair",
				},
				colorChooser:{
					id:"toolColorChooser",
				},
				colorPicker:{
					id:"toolColorPicker",
					cursorOffsetY:15,
				},
				undo:{
					id:"toolUndo",
				},
				redo:{
					id:"toolRedo",
				},
			},
		},
		toolbar:{
			buttonOffsetX:5,
			buttonOffsetY:5,
			buttonWidth:50,
			buttonHeight:40,
			id:"toolbar",
			lineWidth:{
				id:"toolLineWidthButton",
				order:1,
			},
			path:{
				id:"toolPathButton",
				order:2,
			},
			eraser:{
				id:"toolEraserButton",
				order:3,
			},
			line:{
				id:"toolLineButton",
				order:4,
			},
			rect:{
				id:"toolRectButton",
				order:5,
			},
			circle:{
				id:"toolCircleButton",
				order:6,
			},
			select:{
				id:"toolSelectButton",
				order:7,
			},
			colorChooser:{
				id:"toolColorChooserButton",
				order:8,
			},
			colorPicker:{
				id:"toolColorPickerButton",
				order:9,
			},
			undo:{
				id:"toolUndoButton",
				order:10,
			},
			redo:{
				id:"toolRedoButton",
				order:11,
			},
		},
		colorChooser:{
			width:325,
			height:320,
			id:"colorChooser",
			panel:{
				plate:{
					id:"colorPlate",
					className:"colorComponent",
					width:230,
					height:170,
					offsetX:10,
					offsetY:10,
					minLeftOffset:0,
					minTopOffset:1,
					maxLeftOffset:1,
					maxTopOffset:1,
					colorAdjustX:-1,
					colorAdjustY:-2,
					cursor:{
						id:"colorPlateCursor",
						className:"colorElement",
						width:15,
						height:15,
						offsetX:3,
						offsetY:3,
					},
					glass:{
						id:"colorPlateGlass",
						className:"colorElement",
						offsetX:1,
						offsetY:1,
					},
				},
				bright:{
					id:"colorBright",
					className:"colorComponent",
					width:20,
					height:170,
					offsetX:255,
					offsetY:10,
					minLeftOffset:1,
					minTopOffset:2,
					maxLeftOffset:-1,
					maxTopOffset:1,
					colorAdjustX:-1,
					colorAdjustY:-2,
					cursor:{
						id:"colorBrightCursor",
						className:"colorElement",
						offsetX:1,
						offsetY:4,
						height:12,
					},
					glass:{
						id:"colorBrightGlass",
						className:"colorElement",
						offsetX:1,
						offsetY:1,
					},
				},
				opacity:{
					id:"colorOpacity",
					className:"colorComponent",
					width:20,
					height:170,
					offsetX:290,
					offsetY:10,
					minLeftOffset:1,
					minTopOffset:2,
					maxLeftOffset:-1,
					maxTopOffset:1,
					colorAdjustX:-1,
					colorAdjustY:-2,
					cursor:{
						id:"colorOpacityCursor",
						className:"colorElement",
						offsetX:1,
						offsetY:4,
						height:12,
					},
					glass:{
						id:"colorOpacityGlass",
						className:"colorElement",
						offsetX:1,
						offsetY:1,
					},
				},
			},
			info:{
				id:"colorInfo",
				className:"colorComponent",
				width:80,
				height:100,
				offsetX:10,
				offsetY:195,
				padding:5,
				inputWidth:30,
				r:{
					text:{
						id:"colorInfoRText",
						value:"R",
					},
					input:{
						id:"colorInfoRInput",
						className:"colorInput",
					},
				},
				g:{
					text:{
						id:"colorInfoGText",
						value:"G",
					},
					input:{
						id:"colorInfoGInput",
						className:"colorInput",
					},
				},
				b:{
					text:{
						id:"colorInfoBText",
						value:"B",
					},
					input:{
						id:"colorInfoBInput",
						className:"colorInput",
					},
				},
				a:{
					text:{
						id:"colorInfoAText",
						value:"A",
					},
					input:{
						id:"colorInfoAInput",
						className:"colorInput",
					},
				},
			},
			preview:{
				width:50,
				height:55,
				chosen:{
					id:"colorChosen",
					className:"colorComponent",
					offsetX:110,
					offsetY:195,
					text:{
						id:"colorChosenText",
						className:"colorElement",
						value:"New",
						offsetX:5,
						offsetY:40,
					},
				},
				current:{
					id:"colorCurrent",
					className:"colorComponent",
					offsetX:110,
					offsetY:250,
					text:{
						id:"colorCurrentText",
						className:"colorElement",
						value:"Current",
						offsetX:5,
						offsetY:40,
					},
				},
			},
			button:{
				width:75,
				ok:{
					id:"colorButtonOK",
					className:"colorElement",
					value:"OK",
					offsetX:240,
					offsetY:245,
				},
				cancel:{
					id:"colorButtonCancel",
					className:"colorElement",
					value:"Cancel",
					offsetX:240,
					offsetY:280,
				},
			},
		},
		editPanel:{
			id:"editPanelDiv",
			padding:5,
			frame:{
				id:"editPanelFrame",
			},
			cp:{
				scale:{
					className:"editPanelCPScale",
					width:4,
				},
				rotate:{
					id:"editPanelCPRotate",
					offsetY:10,
					width:10,
				},
			},
			block:{
				id:"editPanelBlock",
			},
		},
	},
	source:{
		img:{
			amount:18,
			canvas:{
				tool:{
					colorPicker:{
						cursor:"image/canvas/ColorPicker.png",
					},
				},
			},
			toolbar:{
				button:{
					lineWidth:"image/toolbar/LineWidth.png",
					path:"image/toolbar/Path.png",
					eraser:"image/toolbar/Eraser.png",
					line:"image/toolbar/Line.png",
					rect:"image/toolbar/Rect.png",
					circle:"image/toolbar/Circle.png",
					select:"image/toolbar/Select.png",
					colorChooser:"image/toolbar/ColorChooser.png",
					colorPicker:"image/toolbar/ColorPicker.png",
					undo:"image/toolbar/Undo.png",
					redo:"image/toolbar/Redo.png",
				},
			},
			colorChooser:{
				opacity:"image/colorChooser/opacity.png",
				panel:{
					plate:{
						cursor:"image/colorChooser/cross.png",
					},
					bright:{
						cursor:"image/colorChooser/arrow.png",
					},
					opacity:{
						cursor:"image/colorChooser/arrow.png",
					}
				},
			},
			editPanel:{
				cp:{
					rotate:{
						bg:"image/editPanel/Rotate.png",
						cursor:"image/editPanel/RotateCursor.png",
					},
				},
			},
		},
	},
};